### ISSUE TITLE
Missing the Name for property_id

### ISSUE THREAD

**Issue by HuuuNan** [neelguha/simple-wikidata-db#9]
Hi,

Thanks for the great project! I've noticed that in the extracted JSONL files, there is no name for 'property_id'. Could you please provide some guidance or suggestions on how to accurately extract the name of 'property_id'? Any help would be greatly appreciated!

**Comment by neelguha** [comment]
Hi! 

Unfortunately the JSONL files do not contain the property names, just the property id. You can download the id-to-name mappings separately using this library however: https://github.com/maxlath/wikidata-properties-dumper. 

I hope that helps!

**Comment by HuuuNan** [comment]
Thanks!
